version: "3.7"
services:
  nexus:
    image: sonatype/nexus3:3.6.1
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname==einstein]
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms128m -Xmx512m -XX:MaxDirectMemorySize=512m
    container_name: nexus3
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      -  /mnt/bucket/nexus:/nexus-data