version: "3.7"
services:
  nexus:
    image: sonatype/nexus3:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.hostname==bohr]
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms128m -Xmx512m -XX:MaxDirectMemorySize=256m
    container_name: nexus3
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      -  /mnt/nexus-data:/nexus-data