apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TerenceLiu98/homelab.git
    targetRevision: experimental
    path: platform/auth
    kustomize:
      patches:
        - target:
            group: networking.k8s.io
            version: v1
            kind: Ingress
            name: dex
            namespace: identity
          patch: |-
            - op: replace
              path: /spec/tls/0/secretName
              value: erotica-icu-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
