apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  name: platform-opensandbox-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/opensandbox-group/OpenSandbox.git
    targetRevision: helm/opensandbox/0.2.0
    path: kubernetes/charts/opensandbox-controller
    helm:
      releaseName: opensandbox-controller
      values: |
        namespaceOverride: opensandbox-system
        controller:
          replicaCount: 1
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: opensandbox-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
