apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-socks5
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TerenceLiu98/homelab.git
    targetRevision: experimental
    path: platform/socks5
  destination:
    server: https://kubernetes.default.svc
    namespace: socks5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
