apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TerenceLiu98/homelab.git
    targetRevision: experimental
    path: platform/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

