apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: juicefs-csi-driver
  namespace: kube-system
spec:
  repo: https://juicedata.github.io/charts/
  chart: juicefs-csi-driver
  targetNamespace: kube-system
  valuesContent: |-
    controller:
      replicas: 1
    globalConfig:
      mountPodPatch:
        - hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          mountOptions:
            - cache-dir=/var/jfsCache
            - cache-size=30720
            - free-space-ratio=0.20
            - writeback_cache
            - attr-cache=5
            - entry-cache=5
            - dir-entry-cache=5
            - readdir-cache
            - cache-large-write
            - max-uploads=64
            - prefetch=4
    node:
      hostNetwork: true
      tolerations:
        - operator: Exists
