apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-rwx
provisioner: csi.juicefs.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  juicefs/host-path: /srv/k3s-data/gluster/mounts/gv0/juicefs-objects
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: storage
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: storage
