apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - juicefs-csi.yaml
  - juicefs-format-job.yaml
  - juicefs-storageclass.yaml
  - local-path-thinkpad.yaml
