version: "3"
services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname==bohr]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DEFAULT_WORKSPACE=$DEFAULT_WORKSPACE
      - PASSWORD=$PASSWORD
    volumes:
      - /mnt/nfs/code-server/config:/config
    ports:
      - 8010:8443
    restart: unless-stopped
