apiVersion: v1
kind: Service
metadata:
  name: gost-socks5
  namespace: socks5
spec:
  selector:
    app.kubernetes.io/name: gost-socks5
  ports:
    - name: socks5
      port: 8081
      targetPort: socks5
      protocol: TCP
  # Expose the service on the Optiplex5060 intranet and Tailscale IPs.
  externalIPs:
    - 192.168.2.153
    - 100.118.192.86
