apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensandbox-server
  namespace: opensandbox-system
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - opensandbox.initio.cc
      secretName: initio-cc-tls
  rules:
    - host: opensandbox.initio.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opensandbox-server
                port:
                  number: 80
