apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-watch-ingress-for-tls-sync
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-watch-ingress-for-tls-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-watch-ingress-for-tls-sync
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-read-initio-cc-tls-source
  namespace: kyverno
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - initio-cc-tls
    verbs:
      - get
      - update
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-read-initio-cc-tls-source
  namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-read-initio-cc-tls-source
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: gitea
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: gitea
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-manage-initio-cc-tls
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: argocd
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-manage-initio-cc-tls
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: identity
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: identity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-manage-initio-cc-tls
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: istio-system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-manage-initio-cc-tls
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: chrome
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: chrome
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-manage-initio-cc-tls
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: hephaestus-system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-manage-initio-cc-tls
  namespace: hephaestus-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-manage-initio-cc-tls
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-initio-cc-tls-to-ingress-namespaces
spec:
  admission: true
  background: true
  emitWarning: false
  validationFailureAction: Audit
  rules:
    - name: clone-initio-cc-tls-to-argocd
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - argocd
      generate:
        apiVersion: v1
        kind: Secret
        name: initio-cc-tls
        namespace: argocd
        synchronize: true
        clone:
          namespace: kyverno
          name: initio-cc-tls
        generateExisting: true
    - name: clone-initio-cc-tls-to-gitea
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - gitea
      generate:
        apiVersion: v1
        kind: Secret
        name: initio-cc-tls
        namespace: gitea
        synchronize: true
        clone:
          namespace: kyverno
          name: initio-cc-tls
        generateExisting: true
    - name: clone-initio-cc-tls-to-identity
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - identity
      generate:
        apiVersion: v1
        kind: Secret
        name: initio-cc-tls
        namespace: identity
        synchronize: true
        clone:
          namespace: kyverno
          name: initio-cc-tls
        generateExisting: true
    - name: clone-initio-cc-tls-to-istio-system
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - istio-system
      generate:
        apiVersion: v1
        kind: Secret
        name: initio-cc-tls
        namespace: istio-system
        synchronize: true
        clone:
          namespace: kyverno
          name: initio-cc-tls
        generateExisting: true
    - name: clone-initio-cc-tls-to-opensandbox-system
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - opensandbox-system
      generate:
        apiVersion: v1
        kind: Secret
        name: initio-cc-tls
        namespace: opensandbox-system
        synchronize: true
        clone:
          namespace: kyverno
          name: initio-cc-tls
        generateExisting: true
    - name: clone-initio-cc-tls-to-chrome
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - chrome
      generate:
        apiVersion: v1
        kind: Secret
        name: initio-cc-tls
        namespace: chrome
        synchronize: true
        clone:
          namespace: kyverno
          name: initio-cc-tls
        generateExisting: true
    - name: clone-initio-cc-tls-to-hephaestus-system
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Ingress
              namespaces:
                - hephaestus-system
      generate:
        apiVersion: v1
        kind: Secret
        name: initio-cc-tls
        namespace: hephaestus-system
        synchronize: true
        clone:
          namespace: kyverno
          name: initio-cc-tls
        generateExisting: true
